apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: us.gcr.io/my-project-1518483136546/taco-frontend:latest
        ports:
        - containerPort: 3000
        env:
          - name: "APP_ENV"
            value: production
