apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: taco-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: taco-ip
spec:
  backend:
    serviceName: backend-deployment
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /frontend
        backend:
          serviceName: frontend-deployment
          servicePort: 3000