apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: taco-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: taco-ip
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: frontend-deployment
          servicePort: 3000
      - path: /api/*
        backend:
          serviceName: backend-deployment
          servicePort: 80